### ISSUE TITLE
Commits only changing "Last updated" line are polluting commit history

### ISSUE THREAD

**Issue by McPringle** [minicli/action-contributors#13]
I run the action every night to add new contributors. But if there are no new contributors, it still creates a commit with just an updated "Last updated" line.

Example: https://github.com/komunumo/komunumo-server/commit/8c9985006ce24d906b8b86f849ea80df7c7918f2

If there are no new contributors, I would not expect to update the file at all.

**Comment by pedro-psb** [comment]
As a workaround you can do something like:

```yml
     - name: "Update a projects CONTRIBUTORS file"
        uses: minicli/action-contributors@v3.3

      - name: Check if changes are minimal
        id: check_diff
        run: |
          DIFF_STAT=$(git diff --stat | tail -1 | xargs)  # xargs trims leading spaces
          EXPECTED="1 file changed, 1 insertion(+), 1 deletion(-)"
          if [ "$DIFF_STAT" = "$EXPECTED" ]; then
            echo "skip_pr=true" >> $GITHUB_OUTPUT
          else
            echo "skip_pr=false" >> $GITHUB_OUTPUT
          fi

      - name: Create a PR  # or the commit action
        if: steps.check_diff.outputs.skip_pr == 'false'
        uses: peter-evans/create-pull-request@v3
```
